name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - Dockerfile
      - '**/*.go'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'lean-delivery'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          docker build . --file Dockerfile --tag substitute-env-vars:${{ steps.semantic.outputs.new_release_version }}
          docker push ghcr.io/lean-delivery/substitute-env-vars:${{ steps.semantic.outputs.new_release_version }}
